### ISSUE TITLE
Add recipe page

### ISSUE THREAD

**Issue by d-belleza** [d-belleza/recipe-site#12]
Create add recipe handlebars and javascript

**Comment by melissabcadena** [comment]
Added Handlebars page for Add-Page, but need to figure out how to write route to render this page

**Comment by melissabcadena** [comment]
Also updated the javascript based on the html on add-post.handlebars

**Comment by melissabcadena** [comment]
Added route to render add-post.handlebars page. Still having issues with the page itself though: 

- [x]  main.handlebars is showing 'login' option even though I'm already logged in

- [x] - 'submit' button is not working
